runtime: python37 # or python38 for Python 3.7

instance_class: F2

#env_variables:
#  BUCKET_NAME: "example-gcs-bucket"

handlers:
# Matches requests to /images/... to files in static/images/...
- url: /static
  static_dir: static
- url: /.*
#  script: main.app
  script: auto
  secure: always
  redirect_http_response_code: 301
#  script: auto